name: Create and publish a Docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      # Docker Build and Push step
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: whoami
          registry: ghcr.io
          addLatest: true
          githubOrg: jaehue
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
